trigger:
  - main

pool:
  # vmImage: 'macos-latest'
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '24.x'

stages:
- stage: Build
  displayName: 'Build and Code Quality Checks'
  jobs:
  - job: BuildJob
    steps:
    - task: UseNode@1
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '$(NODE_VERSION)'

    # - script: |
    #     corepack enable
    #     yarn set version berry
    #     echo "Yarn version after update:"
    #     yarn --version
    #   displayName: 'Enable Corepack and Install Yarn Berry'
    # - task: Cache@2
    #   displayName: 'Cache Yarn packages'
    #   inputs:
    #     key: 'yarn | "$(Agent.OS)" | yarn.lock'
    #     restoreKeys: |
    #       yarn | "$(Agent.OS)"
    #       yarn
    #     path: '$(Pipeline.Workspace)/.yarn/cache' # Recommended path for Yarn Berry cache

    - script: |
        yarn install --immutable
        # yarn install --frozen-lockfile
      displayName: 'Install Yarn Dependencies'

    - script: |
        yarn test
      displayName: 'Run Tests'

    - script: |
        yarn prepare
      displayName: 'Build Library'

# - script: yarn publish --non-interactive # Be cautious with automated publishing
#   displayName: 'Publish Library to npm'
#   env:
#     NPM_TOKEN: $(NPM_TOKEN) # Use a secret variable for the npm token