name: "Android Linux Build"
description: "Android Linux Build"
runs:
  using: "composite"
  steps:
    - run: chmod +x example/android/gradlew
      shell: bash
    - run: |
        cd example/android
        ./gradlew assembleRelease --no-daemon --warning-mode all
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: app-release-android
        path: android/app/build/outputs/apk/release/*.apk
